### ISSUE TITLE
Slow search function

### ISSUE THREAD

**Issue by strobba** [Ingenjorsarbete-For-Klimatet/ifk-analyses#2]
To search in the scb db structure in an efficient way, a search function was implemented in python. However there is a request limit on scb's api. Hence, a pause (time.sleep(0.5)) was implemented. This makes of course the search slow. This needs to be fixed in future. 

On solution is to use current solution to write a txt-file, and search in the txt-file. In such a solution the txt-file needs to be updated on some kind of basis.

**Comment by docNord** [comment]
Yes, pause is not a viable long-term solution. If the file is not gargantuous, perhaps we could set up some sort of file check. What is the opinion of @mgcth ?

**Comment by mgcth** [comment]
We could index here on GitHub with a scheduled action that writes a commit to the repo, perhaps. If it is just a text file that is well-defined, I think git should be the perfect tool to version it, and it'll be available to everyone.

We might need a bot for it, which we should have anyway.

**Comment by strobba** [comment]
The file should not be to big. It's just (index, title) and I guess it's not to many rows (<100k?). But maybe the indexing is possible to find in another way outside pyscbwrapper?  

If I implement a function generating the text file, can you set up the rest @mgcth?

**Comment by strobba** [comment]
Ok it was only 4872 rows (instances), a function generating the txt file is now implemented and a function searching in the txt file in the speed of light is also now implemented. See PR for code.
